import csv

csv_writer = csv.writer(open('data.csv', 'w', newline=''))
rows = [
    ['Quantity', 'Card'],
    ['4', 'Goblin Guide'],
    ['4', 'Monastery Swiftspear'],
    ['4', 'Lava Spike'],
    ['4', 'Lightning Bolt'],
    ['4', 'Boros Charm'],
    ['4', 'Lightning Helix'],
    ['4', 'Searing Blaze'],
    ['4', 'Skullcrack'],
    ['4', 'Rift Bolt'],
    ['4', 'Skewer the Critics'],
    ['4', 'Arid Mesa'],
    ['4', 'Bloodstained Mire'],
    ['4', 'Fiery Islet'],
    ['4', 'Inspiring Vantage'],
    ['4', 'Mountain'],
    ['4', 'Sacred Foundry'],
    ['4', 'Scalding Tarn'],
    ['4', 'Sunbaked Canyon'],
    ['4', 'Wooded Foothills'],
    ['4', "Thalia's Lieutenant"],
    ['4', 'Thalia, Guardian of Thraben'],
    ['4', 'Brutal Cathar'],
    ['4', 'Skyclave Apparition'],
    ['4', 'Castle Ardenvale'],
    ['4', 'Eiganjo, Seat of the Empire'],
    ['4', 'Mutavault'],
    ['4', 'Elvish Mystic'],
    ['4', 'Llanowar Elves'],
    ['3', 'Kiora, Behemoth Beckoner'],
    ['1', 'Oath of Nissa'],
    ['2', 'Boseiju, Who Endures'],
    ['20', 'Forest'],
    ['4', 'Nykthos, Shrine to Nyx'],
    ['2', "Tormod's Crypt"],
    ['2', 'Pithing Needlex'],
    ['4', 'Damping Sphere'],
    ['4', "Esika's Chariot"],
    ['4', 'Eidolon of the Great Revel'],
    ['4', 'Path to Exile'],
    ['3', 'Deflecting Palm'],
    ['4', 'Roiling Vortex'],
    ['3', 'Sanctifier en-Vec'],
    ['4', 'Smash to Smithereens'],
    ['2', 'Exquisite Firecraft'],
    ['4', 'Wear // Tear']
]

csv_writer.writerows(rows)
